Unifik\MediaBundle\Entity\Folder:
    type: entity
    table: MediaFolder
    repositoryClass: Unifik\MediaBundle\Entity\FolderRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    lifecycleCallbacks: {  }
    oneToMany:
        children:
            targetEntity: Unifik\MediaBundle\Entity\Folder
            mappedBy: parent
        medias:
            targetEntity: Unifik\MediaBundle\Entity\Media
            mappedBy: folder
    manyToOne:
        parent:
            targetEntity: Unifik\MediaBundle\Entity\Folder
            inversedBy: children