Egzakt\MediaBundle\Entity\Image:
    type: entity
    table: null
    fields:
        width:
            type: integer
            nullable: true
        height:
            type: integer
            nullable: true
        attr:
            type: string
            length: 50
            nullable: true
    lifecycleCallbacks: { }