Egzakt\MediaBundle\Entity\Image:
    type: entity
    table: null
    fields:
        width:
            type: integer
        height:
            type: integer
        attr:
            type: string
            length: 50
    lifecycleCallbacks: { }