Flexy\MediaBundle\Entity\Media:
    type: entity
    table: null
    repositoryClass: Flexy\MediaBundle\Entity\MediaRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        type:
            type: string
            length: 255
        mediaPath:
            type: string
            length: 255
            nullable: true
        url:
            type: string
            length: 255
            nullable: true
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        description:
            type: text
            nullable: true
        caption:
            type: string
            length: 255
            nullable: true
        mimeType:
            type: string
            length: 255
            nullable: true
        size:
            type: decimal
            nullable: true
        width:
            type: integer
            nullable: true
        height:
            type: integer
            nullable: true
        attr:
            type: string
            length: 50
            nullable: true
    lifecycleCallbacks: {  }
    oneToOne:
        thumbnail:
            targetEntity: Flexy\MediaBundle\Entity\Media
            mappedBy: parentMedia
            onDelete: cascade
        parentMedia:
            targetEntity: Flexy\MediaBundle\Entity\Media
            inversedBy: thumbnail
            joinColumn:
                name: parentMedia
                referencedColumnName: id
                onDelete: cascade