Egzakt\MediaBundle\Entity\Video:
    type: entity
    table: null
    fields:
    lifecycleCallbacks: {  }
    oneToOne:
        thumbnail:
            targetEntity: Image
            mappedBy: video
            cascade: [persist]
            orphanRemoval: true
