Egzakt\MediaBundle\Entity\Video:
    type: entity
    table: null
    fields:
        width:
            type: integer
        height:
            type: integer
        url:
            type: string
            length: 255
    lifecycleCallbacks: {  }
