egzakt_media_backend_media:
    pattern:  /type/{type}
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:index", type: image }

egzakt_media_backend_media_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:edit", id: 0 }

egzakt_media_backend_media_duplicate:
    pattern:  /{id}/duplicate
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:duplicate" }

egzakt_media_backend_media_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:delete" }

egzakt_media_backend_media_create_video:
    pattern:  /create/video
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Video:create" }

egzakt_media_backend_media_create:
    pattern:  /create
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:create" }

egzakt_media_backend_media_image_edit:
    pattern: /{id}/image/edit
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:updateImage" }


