egzakt_media_backend_media:
    pattern:  /
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:index" }

egzakt_media_backend_media_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:edit", id: 0 }

egzakt_media_backend_media_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:delete" }

egzakt_media_backend_media_create:
    pattern:  /create
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:create" }

egzakt_media_backend_media_pixlr_open:
    pattern: /{id}/pixlr/open
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Image:openPixlr" }

egzakt_media_backend_media_pixlr_edit:
    pattern: /{id}/pixlr/edit
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Image:editPixrl" }


