# Media
egzakt_media_backend_media:
    pattern:  /
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:media" }

egzakt_media_backend_media_pager:
    pattern:  /media/page
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:mediaPager" }

egzakt_media_backend_media_select_pager:
    pattern:  /media-select-pager
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:mediaSelectPager" }
    options:
        expose: true

# Upload
egzakt_media_backend_media_upload:
    pattern: /upload
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Upload:upload" }
    options:
        expose: true

# Image
egzakt_media_backend_image_edit:
    pattern:  /image/{id}/edit
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Image:edit"}

egzakt_media_backend_image_aviary_edit:
    pattern: /image/{id}/update/
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Image:updateImage" }

egzakt_media_backend_image_duplicate:
    pattern:  /{id}/duplicate
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:duplicate" }

egzakt_media_backend_image_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:delete" }

# Document
egzakt_media_backend_document_edit:
    pattern:  /document/{id}/edit
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Document:edit", id: 0 }

egzakt_media_backend_document_duplicate:
    pattern:  /{id}/duplicate
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:duplicate" }

egzakt_media_backend_document_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:delete" }

# Video
egzakt_media_backend_video_edit:
    pattern:  /video/{id}/edit
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Video:edit", id: 0 }

egzakt_media_backend_video_duplicate:
    pattern:  /{id}/duplicate
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:duplicate" }

egzakt_media_backend_video_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:delete" }

# Embed Video

egzakt_media_backend_embed_video_create:
    pattern:  /embedvideo/create
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/EmbedVideo:create", id: 0 }

egzakt_media_backend_embed_video_edit:
    pattern:  /embedvideo/{id}/edit
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/EmbedVideo:edit", id: 0 }

egzakt_media_backend_embed_video_duplicate:
    pattern:  /{id}/duplicate
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:duplicate" }

egzakt_media_backend_embed_video_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EgzaktMediaBundle:Backend/Media/Media:delete" }