# Media
unifik_media_backend_media:
    pattern:  /
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/Media:media" }

unifik_media_backend_load:
    pattern:  /load
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/Media:load" }
    options:
        expose: true

unifik_media_backend_move:
    pattern:  /move
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/Media:move" }
    options:
        expose: true

unifik_media_backend_createFolder:
    pattern:  /create-folder
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/Media:createFolder" }
    options:
        expose: true

unifik_media_backend_deleteFolder:
    pattern:  /delete-folder
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/Media:deleteFolder" }
    options:
        expose: true

unifik_media_backend_renameFolder:
    pattern:  /rename-folder
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/Media:renameFolder" }
    options:
        expose: true

unifik_media_backend_deleteMedia:
    pattern:  /delete-media
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/Media:deleteMedia" }
    options:
        expose: true

unifik_media_backend_duplicate:
    pattern:  /duplicate
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/Media:duplicate" }
    options:
        expose: true

unifik_media_backend_associations:
    pattern:  /associations
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/Media:associations" }
    options:
        expose: true

unifik_media_backend_associations_replace:
    pattern:  /associations-replace
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/Media:associationsReplace" }
    options:
        expose: true

unifik_media_backend_modal_search:
    pattern:  /modal-search
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/Media:modalSearch" }
    options:
        expose: true

# Upload
unifik_media_backend_media_upload:
    pattern: /upload
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/Upload:upload" }
    options:
        expose: true

# Image
unifik_media_backend_image_edit:
    pattern:  /image-edit
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/Image:edit" }
    options:
        expose: true

unifik_media_backend_image_aviary_edit:
    pattern: /image/{id}/update/
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/Image:updateImage" }

# Document
unifik_media_backend_document_edit:
    pattern:  /document-edit
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/Document:edit" }
    options:
        expose: true

# Video
unifik_media_backend_video_edit:
    pattern:  /video-edit
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/Video:edit" }
    options:
        expose: true

# Embed Video

unifik_media_backend_embed_video_create:
    pattern:  /embedvideo/create
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/EmbedVideo:create", id: 0 }
    options:
        expose: true

unifik_media_backend_embed_video_edit:
    pattern:  /embedvideo-edit
    defaults: { _controller: "UnifikMediaBundle:Backend/Media/EmbedVideo:edit" }
    options:
        expose: true

# Imagine
_imagine:
    resource: .
    type:     imagine