parameters:
    egzakt_media.parser.class: Egzakt\MediaBundle\Lib\ExternalMediaParser

    egzakt_media.youtube_parser.class: Egzakt\MediaBundle\Lib\YoutubeVideoParser
    egzakt_media.vimeo_parser.class: Egzakt\MediaBundle\Lib\VimeoVideoParser

    egzakt_media.parser_extension.class: Egzakt\MediaBundle\Extensions\ExternalMediaParserExtension

    egzakt_media.form.type.media_select.class: Egzakt\MediaBundle\Form\MediaSelectType

    egzakt_media.listener.media_change.class: Egzakt\MediaBundle\Listener\MediaChangeListener

services:

    # Media Parser
    egzakt_media.parser:
        class: %egzakt_media.parser.class%

    # Youtube Media Parser
    egzakt_media.media_parser.youtube_parser:
        class: %egzakt_media.youtube_parser.class%
        tags:
            - { name: egzakt_media.parser }

    # Vimeo Media Parser
    egzakt_media.media_parser.vimeo_parser:
        class: %egzakt_media.vimeo_parser.class%
        tags:
            - { name: egzakt_media.parser }

    # Twig Media Parser Extension
    egzakt_media.parser_extension:
        class: %egzakt_media.parser_extension.class%
        arguments: [@egzakt_media.parser]
        tags:
            - { name: twig.extension }

    egzakt_system.form.type.media_select:
            class: %egzakt_media.form.type.media_select.class%
            tags:
              - { name: form.type, alias: media_select }

    egzakt_media.media_change_listener:
            class: %egzakt_media.listener.media_change.class%
            tags:
              - { name: doctrine.event_subscriber, connection: default }