parameters:
    unifik_media.parser.class: Unifik\MediaBundle\Lib\ExternalMediaParser
    unifik_media.youtube_parser.class: Unifik\MediaBundle\Lib\YoutubeVideoParser
    unifik_media.vimeo_parser.class: Unifik\MediaBundle\Lib\VimeoVideoParser
    unifik_media.parser_extension.class: Unifik\MediaBundle\Extensions\ExternalMediaParserExtension
    unifik_media.form.type.media_select.class: Unifik\MediaBundle\Form\MediaSelectType
    unifik_media.listener.media_change.class: Unifik\MediaBundle\Listener\MediaChangeListener
    unifik_media.listener.folder_deletable.class: Unifik\MediaBundle\Listener\FolderDeletableListener


services:

    # Media Parser
    unifik_media.parser:
        class: %unifik_media.parser.class%

    # Youtube Media Parser
    unifik_media.media_parser.youtube_parser:
        class: %unifik_media.youtube_parser.class%
        tags:
            - { name: unifik_media.parser }

    # Vimeo Media Parser
    unifik_media.media_parser.vimeo_parser:
        class: %unifik_media.vimeo_parser.class%
        tags:
            - { name: unifik_media.parser }

    # Twig Media Parser Extension
    unifik_media.parser_extension:
        class: %unifik_media.parser_extension.class%
        arguments: [@unifik_media.parser]
        tags:
            - { name: twig.extension }

    unifik_system.form.type.media_select:
        class: %unifik_media.form.type.media_select.class%
        tags:
          - { name: form.type, alias: media_select }

    unifik_media.media_change_listener:
        class: %unifik_media.listener.media_change.class%
        tags:
          - { name: doctrine.event_subscriber, connection: default }

    mynamespacebundle.entitylistener:
        class: %unifik_media.listener.folder_deletable.class%
        arguments: [ @translator ]
        tags:
          - { name: unifik_system.deletable, entity: Unifik\MediaBundle\Entity\Folder }