<?php

namespace Unifik\MediaBundle\Entity;

use Unifik\SystemBundle\Lib\BaseEntityRepository;

/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FolderRepository extends BaseEntityRepository
{
}